apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: demo-pdb-vs
spec:
  hosts:
    - "*"
  gateways:
    - demo-pdb-gateway
  http:
    - match:
        - headers:
            x-canary:
              exact: "true"
      route:
        - destination:
            host: demo-pdb-service
            subset: v2
    - route:
        - destination:
            host: demo-pdb-service
            subset: v1
