apiVersion: v1
kind: Service
metadata:
  name: demo-pdb-shadow-service
  namespace: default
spec:
  type: ClusterIP
  selector:
    pod: demo-pdb-pod
    aion-version: shadow
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
