apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: demo-pdb-dr
  namespace: default
spec:
  host: demo-pdb-service.default.svc.cluster.local
  subsets:
    - name: anchor
      labels:
        aion-version: anchor
    - name: shadow
      labels:
        aion-version: shadow
