apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: demo-pdb-service-vs
  namespace: default
spec:
  hosts:
  - "*"
  gateways:
  - demo-pdb-gateway
  http:
  - match:
    - headers:
        x-aion-preview:
          exact: "true"
      uri:
        prefix: /public
    route:
    - destination:
        host: demo-pdb-service.default.svc.cluster.local
        subset: shadow
        port:
          number: 80
      headers:
        request:
          set:
            # ESTO ES LA CLAVE: Enga√±amos a la app para que crea que la llaman localmente
            Host: demo-pdb-service.default.svc.cluster.local
            x-forwarded-proto: http
  - match:
    - uri:
        prefix: /public
    route:
    - destination:
        host: demo-pdb-service.default.svc.cluster.local
        subset: anchor
        port:
          number: 80
      headers:
        request:
          set:
            Host: demo-pdb-service.default.svc.cluster.local
            x-forwarded-proto: http