apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo-pdb-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: aion.local
      http:
        paths:
          - path: /(public/.*)
            pathType: Prefix
            backend:
              service:
                name: demo-pdb-service
                port:
                  number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo-pdb-ingress-canary
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/canary: "true"
    nginx.ingress.kubernetes.io/canary-by-header: "x-aion-version"
    nginx.ingress.kubernetes.io/canary-by-header-value: "v2"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: aion.local
      http:
        paths:
          - path: /(public/.*)
            pathType: Prefix
            backend:
              service:
                name: demo-pdb-service-shadow
                port:
                  number: 80
