apiVersion: v1
kind: Service
metadata:
  name: demo-pdb-service
spec:
  selector:
    pod: demo-pdb-pod # Esto atrapa TANTO a Anchor como a Shadow. Â¡Correcto!
  ports:
    - name: http
      port: 80
      targetPort: 8080 # Puerto de Spring Boot