apiVersion: v1
kind: Service
metadata:
  name: demo-pdb-service
  namespace: default
spec:
  selector:
    pod: demo-pdb-pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
