apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: demo-pdb-service-vs
  namespace: default
spec:
  hosts:
    - "*"
  gateways:
    - demo-pdb-gateway
  http:
    - match:
        - headers:
            x-aion-preview:
              exact: "true"
          uri:
            prefix: /public
      rewrite:
        uri: /public/hello
      route:
        - destination:
            host: demo-pdb-shadow-service.default.svc.cluster.local
            port:
              number: 80
    - match:
        - uri:
            prefix: /public
      rewrite:
        uri: /public/hello
      route:
        - destination:
            host: demo-pdb-service.default.svc.cluster.local
            port:
              number: 80
    - match:
        - uri:
            prefix: /
      rewrite:
        uri: /public/hello
      route:
        - destination:
            host: demo-pdb-service.default.svc.cluster.local
            port:
              number: 80
