apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: demo-pdb-service-vs
  namespace: default
spec:
  hosts:
  - "*"
  gateways:
  - demo-pdb-gateway
  http:
  # REGLA 1: Tráfico Shadow (Si tiene el Header)
  - match:
    - headers:
        x-aion-preview:
          exact: "true"
      uri:
        prefix: /public
    route:
    - destination:
        host: demo-pdb-service.default.svc.cluster.local
        subset: shadow
        port:
          number: 80
      headers:
        request:
          set:
            # Truco para que Spring Boot no rechace la petición
            Host: demo-pdb-service.default.svc.cluster.local
  
  # REGLA 2: Tráfico Anchor (Por defecto)
  - match:
    - uri:
        prefix: /public
    route:
    - destination:
        host: demo-pdb-service.default.svc.cluster.local
        subset: anchor
        port:
          number: 80
      headers:
        request:
          set:
            Host: demo-pdb-service.default.svc.cluster.local