apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-pdb-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Adan2804/demo-microservice-pdb.git
    targetRevision: HEAD
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  ignoreDifferences:
    - group: aion.flux.io
      kind: AionRollout
      name: demo-pdb-rollout
      jsonPointers:
        - /spec/migrationState
        - /spec/replicas
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
